title:            ISDPRL
school:           UBCO Okanagan
description:      "Intelligent Sensing, Diagnostic and Prognostic Research Lab"
logo:             UBC_Logo.png
logo_white:       UBC_Logo_White.png
name: Awesome Research Group
url: " "

exclude: [bibble, README.md, Makefile, screenshot.png]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables]

# colorize code snippets with the pygments module
pygments: true

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
    - {key: faculty, name: Faculty}
    - {key: grad, name: Graduate Students}

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: " "
# base: "/Lab_WebPage"
# url: "http://lukeandshuo.github.io"

# Navigation bar links.
links:
    - title: Home
      url: /
    - title: People
      url: /people/
    - title: Research
      url: /research/
    - title: Publications
      url: /publications/
    - title: Code
      url: /code/
